backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: src/img/uploads
public_folder: /img/uploads
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '/src/blog'
    create: true
    slug: '{{year}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'post_img', widget: 'image' }
      - { label: 'Image Alt Text', name: 'post_imgAlt', widget: 'string' }
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Page Description', name: 'page_desc', widget: 'text' }
      - { label: 'Post Body', name: 'body', widget: 'markdown' }
      - {
          label: 'permalink',
          name: 'permalink',
          widget: 'hidden',
          default: '/{{ title | slugify }}/',
        }
