backend:
  name: git-gateway
  branch: main
media_folder: 'src/img/uploads'
public_folder: '/img/uploads'
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '/src/blog'
    create: true
    slug: '{{year}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'post_img', widget: 'image' }
      - { label: 'Image Alt Text', name: 'post_imgAlt', widget: 'string' }
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Post Body', name: 'body', widget: 'markdown' }
